# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:28:49+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from starlette.requests import Request

app = MCPProxy(
    description='Datumbox offers a Machine Learning platform composed of 14 classifiers and Natural Language processing functions. Functions include sentiment analysis, topic classification, readability assessment, language detection, and much more.',
    title='api.datumbox.com',
    version='1.0',
    servers=[{'url': 'http://api.datumbox.com/'}],
)


@app.post(
    '/1.0/AdultContentDetection.json',
    description=""" The Adult Content Detection function classifies the documents as adult or noadult based on their context. It can be used to detect whether a document contains content unsuitable for minors. """,
    tags=['content_classification'],
)
def adult_content_detection(request: Request):
    """
    Classifies the Document as adult or noadult
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/CommercialDetection.json',
    description=""" The Commercial Detection function labels the documents as commercial or non-commercial based on their keywords and expressions. It can be used to detect whether a website is commercial or not. """,
    tags=['content_classification'],
)
def commercial_detection(request: Request):
    """
    Classifies the Document as commercial or nocommercial
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/DocumentSimilarity.json',
    description=""" The Document Similarity function estimates the degree of similarity between two documents. It can be used to detect duplicate webpages or detect plagiarism. """,
    tags=['document_similarity_and_keywords'],
)
def document_similarity(request: Request):
    """
    Estimates the similarity between 2 Documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/EducationalDetection.json',
    description=""" The Educational Detection function classifies the documents as educational or non-educational based on their context. It can be used to detect whether a website is educational or not. """,
    tags=['content_classification'],
)
def educational_detection(request: Request):
    """
    Classifies the Document as educational or noeducational
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/GenderDetection.json',
    description=""" The Gender Detection function identifies if a particular document is written-by or targets-to a man or a woman based on the context, the words and the idioms found in the text. """,
    tags=['content_classification'],
)
def gender_detection(request: Request):
    """
    Gender Detection Service
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/KeywordExtraction.json',
    description=""" The Keyword Extraction function enables you to extract from an arbitrary document all the keywords and word-combinations along with their occurrences in the text. """,
    tags=['document_similarity_and_keywords'],
)
def keyword_extraction(request: Request):
    """
    Extracts the Keywords of the Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/LanguageDetection.json',
    description=""" The Language Detection function identifies the natural language of the given document based on its words and context. This classifier is able to detect 96 different languages. """,
    tags=['language_detection_and_readability'],
)
def language_detection(request: Request):
    """
    Identifies the Language of the Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/ReadabilityAssessment.json',
    description=""" The Readability Assessment function determines the degree of readability of a document based on its terms and idioms. The texts are classified as basic, intermediate and advanced depending their difficulty. """,
    tags=['language_detection_and_readability'],
)
def readability_assessment(request: Request):
    """
    Evaluates the Readability of the Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/SentimentAnalysis.json',
    description=""" The Sentiment Analysis function classifies documents as positive, negative or neutral (lack of sentiment) depending on whether they express a positive, negative or neutral opinion. """,
    tags=['sentiment_evaluation', 'subjectivity_analysis_and_topic_classification'],
)
def sentiment_analysis(request: Request):
    """
    Identifies the Sentiment of the Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/SpamDetection.json',
    description=""" The Spam Detection function labels documents as spam or nospam by taking into account their context. It can be used to filter out spam emails and comments. """,
    tags=['content_classification'],
)
def spam_detection(request: Request):
    """
    Classifies the Document as spam or nospam
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/SubjectivityAnalysis.json',
    description=""" The Subjectivity Analysis function categorizes documents as subjective or objective based on their writing style. Texts that express personal opinions are labeled as subjective and the others as objective. """,
    tags=['subjectivity_analysis_and_topic_classification', 'content_classification'],
)
def subjectivity_analysis(request: Request):
    """
    Classifies Document as Subjective or Objective
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/TextExtraction.json',
    description=""" The Text Extraction function enables you to extract the important information from a given webpage. Extracting the clear text of the documents is an important step before any other analysis. """,
    tags=['content_classification'],
)
def text_extraction(request: Request):
    """
    Extracts the clear text from Webpage
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/TopicClassification.json',
    description=""" The Topic Classification function assigns documents in 12 thematic categories based on their keywords, idioms and jargon. It can be used to identify the topic of the texts. """,
    tags=['content_classification', 'subjectivity_analysis_and_topic_classification'],
)
def topic_classification(request: Request):
    """
    Identifies the Topic of the Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/1.0/TwitterSentimentAnalysis.json',
    description=""" The Twitter Sentiment Analysis function allows you to perform Sentiment Analysis on Twitter. It classifies the tweets as positive, negative or neutral depending on their context. """,
    tags=['sentiment_evaluation'],
)
def twitter_sentiment_analysis(request: Request):
    """
    Identifies the Sentiment of Twitter Messages
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
